// https://tailwindcss.com/docs/customizing-colors
export const Decks = [
  {
    icon: "🐕",
    title: "Animals",
    bgColor: "#fecaca",
    textColor: "#dc2626",
    cards: [
      "Cat",
      "Dog",
      "Cow",
      "Lion",
      "Tiger",
      "Kangaroo",
      "Hyena",
      "Camel",
      "Giraffe",
      "Crocodile",
      "Sloth",
      "Polar Bear",
      "Sea Lion",
      "Sea Horse",
      "Horse",
    ],
  },
  {
    icon: "👰🏼‍♀️",
    title: "Shaadi",
    bgColor: "#fde68a",
    textColor: "#d97706",
    cards: [
      "Bahu",
      "Sharara",
      "Pan",
      "Dulhan",
      "Sagai / Mangani",
      "Sasur",
      "Saas",
      "Dhoti",
      "Lehnga",
      "Shehrwaani",
      "Bindi",
      "Dulha",
      "Dhol",
      "Mangal Sutra",
      "Caterer",
      "Ghena / Haar",
      "Vidai",
      "Mandip",
      "Jhoomar",
      "Dholki",
      "Dj",
      "Ghajray",
      "Praposal",
      "Sangeet",
      "Mehendi",
      "Haldi",
      "Reception",
    ],
  },
  {
    icon: "🇮🇳",
    title: "Countries",
    bgColor: "#bae6fd",
    textColor: "#0284c7",
    cards: [
      "India",
      "United States of America",
      "Thailand",
      "Lion",
      "Tiger",
      "Kangaroo",
    ],
  },
  {
    icon: "🎬",
    title: "Stars",
    bgColor: "#d9f99d",
    textColor: "#65a30d",
    cards: [
      "Amitabh Bachchan",
      "Saif Ali Khan",
      "Jeetendra",
      "Anupam Kher",
      "Feroz Khan",
      "Arshad Warsi",
    ],
  },
];
